version: "3.7"
services:
  mlflow:
    image: keras_mlflow
    build:
      context: ./
      dockerfile: mlflow.Dockerfile
    container_name: mlflow
    # command: "mlflow server \
    #         --backend-store-uri sqlite:///mlruns/mlflow.db \
    #         --default-artifact-root ./mlruns/artifacts \
    #         --host 0.0.0.0"
    command: "mlflow server \
        --host 0.0.0.0 \
        --backend-store-uri sqlite:///mlruns/mlflow.db \
        --serve-artifacts \
        --artifacts-destination gs://desafio_keras_bucket/mlruns/"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns  # mlflow reads from mlruns
      - ./secrets:/secrets

  streamlit:
    image: keras_streamlit
    build:
      context: ./
      dockerfile: streamlit.Dockerfile
    container_name: streamlit
    command: "streamlit run /streamlit/app.py"
    ports:
      - "8501:8501"
    volumes:
      - ./data:/streamlit/data  # mlflow reads from mlruns
      - ./mlruns:/streamlit/mlruns
      - ./secrets:/streamlit/secrets