FROM python:3.9

LABEL app="Keras_MLFlow" 

ENV VIRTUAL_ENV=.venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./secrets/keras-356322-76c4c7c6a3ee.json ./secrets/keras-356322-76c4c7c6a3ee.json
COPY ./Procfile ./Procfile

ENV MLFLOW_GCS_DEFAULT_TIMEOUT=-1
ENV GOOGLE_APPLICATION_CREDENTIALS=./secrets/keras-356322-76c4c7c6a3ee.json

COPY ./requirements-mlflow.txt ./
RUN pip3 install --upgrade pip && pip3 install -r requirements-mlflow.txt

RUN mkdir ./mlruns
RUN chmod 777 -R ./mlruns

EXPOSE 5000

VOLUME ./mlruns
VOLUME ./secrets

ENV BACKEND_URI sqlite:///mlruns/mlflow.db
ENV ARTIFACTS_DESTINATION gs://desafio_keras_bucket/mlruns/

CMD mlflow server --backend-store-uri ${BACKEND_URI} --serve-artifacts --artifacts-destination ${ARTIFACTS_DESTINATION} --host 0.0.0.0 -p ${PORT}